name = "kcodes-maze"
main = "src/index.tsx"
compatibility_date = "2026-03-28"

[[d1_databases]]
binding = "DB"
database_name = "wiki-race"
database_id = "c60569b1-2694-4486-a089-fdf8ef301f7b"

[[rules]]
type = "Data"
globs = ["**/*.woff2", "**/*.ttf"]
fallthrough = false
