name = "wiki-race"
main = "src/index.tsx"
compatibility_date = "2026-03-28"

[[d1_databases]]
binding = "DB"
database_name = "wiki-race"
database_id = "c60569b1-2694-4486-a089-fdf8ef301f7b"

[[rules]]
type = "Data"
globs = ["**/*.jpg", "**/*.woff2", "**/*.ttf"]
fallthrough = false

[[unsafe.bindings]]
name = "RL_PLAYFREE"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "RL_REGISTER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 5, period = 60 }

[[unsafe.bindings]]
name = "RL_LOGIN"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 20, period = 60 }
